
# History

\framesubtitle{R[Name redacted], findata.org, Rblpapi}

Over multiple slides:

- Screenshot / title of 2004 talk 

- Screenshot / title of findata.org

- Screenshot of \url{http://www.bloomberglabs.com/api} and/or \texttt{.../documentation/}

- Mention passage C to Java to C++

- APIs now 1st-class citizens, multiple languages + OSs

- Mention (ambitious) plans by Bbg to have the API to be ``generic'' for
multiple backends, publishing
